### ISSUE TITLE
Flash player 

### ISSUE THREAD

**Issue by ibrahemesam** [wy3/cefau3#2]
How can I enable flash player in  CEF au3

**Comment by wy3** [comment]
Hi,

First, you need sync **cefau3** source and rebuild it (or put `autoit3/cefau3/*` & `release/cefau3.dll` to your program).

1. Implement `OnBeforeCommandLineProcessing` from `CefApp`

```au3
$cef_app.OnBeforeCommandLineProcessing = __OBCLP

func __OBCLP($process_type, $command_line)

end
```

2. Enable plugins support via `CefBrowserSettings`

```au3
$browser_settings.plugins = 1
$browser_settings.webgl = 1 ; enable webGL
```

3. Setup flash player
- Download flash plugin library (.dll), [click here](https://www.dll-files.com/pepflashplayer.dll.html) or search [pepflashplayer.dll](https://google.com/search?q=pepflashplayer.dll) on Google. For exmaple, I download `pepflashplayer.dll` (32bit - v23.0.0.162) and put it in `C:\pepflashplayer.dll`.
- On `__OBCLP` function, add following code:

```au3
    ...
    $command_line.AppendSwitch(' --enable-system-flash=1 ')
    $command_line.AppendSwitchWithValue('ppapi-flash-path', 'C:\\pepflashplayer.dll')
    $command_line.AppendSwitchWithValue('ppapi-flash-version', '23.0.0.162')
    $command_line.AppendSwitchWithValue('plugin-policy', 'allow')
```

**Comment by ibrahemesam** [comment]
sorry for my late
----------------
I did as you say
 
`$cef_app.OnBeforeCommandLineProcessing = __OBCLP
$browser_settings.plugins = 1
$browser_settings.webgl = 1 ; enable webGL

func __OBCLP($process_type, $command_line)
    $command_line.AppendSwitch(' --enable-system-flash=1 ')
    $command_line.AppendSwitchWithValue('ppapi-flash-path', @ScriptDir '\pepflashplayer.dll')
    $command_line.AppendSwitchWithValue('ppapi-flash-version', '28.0.0.137')
    $command_line.AppendSwitchWithValue('plugin-policy', 'allow')
EndFunc `

, but the script stops here
![image](https://user-images.githubusercontent.com/43931249/51458164-e9e7f380-1d5c-11e9-8cb1-bf55d4e66e1b.png)

**Comment by wy3** [comment]
I think `$browser_settings` is not declared or it is not an object, so you cannot invoke dispatch.

```au3
global $browser_settings = $cef.new("BrowserSettings")
```

You can see that.

https://github.com/wy3/cefau3/blob/cdc6b196840cd857d62c625be10de344045632f6/autoit3/cefau3/cefau3.au3#L157-L161

**Comment by wy3** [comment]
Are you using the latest Cefau3 version?
The previous version is not supported pre-commandline processing.

> 
> First, you need sync **cefau3** source and rebuild it (or put `autoit3/cefau3/*` & `release/cefau3.dll` to your program).
>

**Comment by wy3** [comment]
Please check two files `$(repo)/release/` [**`cefau3.dll`**](https://github.com/wy3/cefau3/tree/master/release) and your **`cefau3.dll`**.
Is it one?

> btw
> AutoIt bindings is my failure, that is so low and bad performance, I cannot continue to develop this project. I'm so sorry about that.

**Comment by ibrahemesam** [comment]
yes,it is
=====
![image](https://user-images.githubusercontent.com/43931249/51519768-947a1800-1e2a-11e9-8b6c-cedaae05ebde.png)
![image](https://user-images.githubusercontent.com/43931249/51519800-aa87d880-1e2a-11e9-91ff-1de737b5daf6.png)
====
`please, if you want to make new version,don't forget to add flash player to it`

**Comment by wy3** [comment]
Okay, please try [my binaries here](https://secufiles.com/ivdJ/cef_autoit3.zip) (only for x86, I tested on Windows 7 and 10 32bit & 64bit).

**Comment by ibrahemesam** [comment]
still not working
![image](https://user-images.githubusercontent.com/43931249/51566981-ad241580-1e9e-11e9-91ec-bf0e615379e4.png)

**Comment by wy3** [comment]
> Cefau3 is not stable, flash is a third party, it maybe crash!.
### Please try this.
```au3
$cef_app.OnBeforeCommandLineProcessing = __OBCLP ; set commandline processing before init app
$cef.Initialize(...) ; /////////////////////
...
#Region init flash player
$cef_bs.plugins = 1
$cef_bs.webgl = 1 ; enable webGL

func __OBCLP($process_type, $command_line)
    $command_line = CefCommandLine_Create($command_line) ; create commandline object
    $command_line.AppendSwitch(' --type=ppapi --enable-system-flash=1 ')
    $command_line.AppendSwitchWithValue('ppapi-flash-path', 'C:\pepflashplayer.dll')
    $command_line.AppendSwitchWithValue('ppapi-flash-version', '25.0.0.171')
    $command_line.AppendSwitchWithValue('plugin-policy', 'allow')
endfunc
#EndRegion
...
global $url = 'https://google.com'
$cef.CreateBrowser($cef_wininfo.__ptr, $cef_client.__ptr, $url, $cef_bs.__ptr, Null)
...
```

**Comment by ibrahemesam** [comment]
what should I put here
![image](https://user-images.githubusercontent.com/43931249/51585829-8e943d80-1ee3-11e9-9744-ea15155d368c.png)

**Comment by wy3** [comment]
This line is from example, `$cef_app.OnBeforeCommandLineProcessing` must be set above this line.

**Comment by wy3** [comment]
> > Cefau3 is not stable, and flash is a third party, it maybe crash. You must run example on compiled executable.
> 
> ### Please try this.
> ```autoit
> $cef_app.OnBeforeCommandLineProcessing = __OBCLP ; set commandline processing before init app
> $cef.Initialize(...) ; /////////////////////
> ...
> #Region init flash player
> $cef_bs.plugins = 1
> $cef_bs.webgl = 1 ; enable webGL
> 
> func __OBCLP($process_type, $command_line)
>     $command_line = CefCommandLine_Create($command_line) ; create commandline object
>     $command_line.AppendSwitch(' --type=ppapi --enable-system-flash=1 ')
>     $command_line.AppendSwitchWithValue('ppapi-flash-path', 'C:\pepflashplayer.dll')
>     $command_line.AppendSwitchWithValue('ppapi-flash-version', '25.0.0.171')
>     $command_line.AppendSwitchWithValue('plugin-policy', 'allow')
> endfunc
> #EndRegion
> ...
> global $url = 'https://google.com'
> $cef.CreateBrowser($cef_wininfo.__ptr, $cef_client.__ptr, $url, $cef_bs.__ptr, Null)
> ...
> ```
